### ISSUE TITLE
Any option to do fingerprint authentication without showing the bottomsheet?

### ISSUE THREAD

**Issue by waqas-334** [BharathVishal/Biometric-Authentication-Android#1]
Hey, your repository is very helpful. However, I was wondering if we can take the user fingerprint without prompting through a bottom sheet. Actually, I am building a vault that is disguised as a calculator, and when the user enables Fingerprint I don't want the app to show a prompt, just read the fingerprint in the background and valid then navigate to vault activity. But your library only reads via prompt. Please let me know if there is any possibility of achieving that.

Thank you

**Comment by BharathVishal** [comment]
Hi, 
Apologies for the late reply. The fingerprint prompt displayed at the bottom of the screen is the Android system's fingerprint prompt initialized using Biometric.PromptInfo.Builder(). The method authenticate() in BiometricPrompt invokes the bottom sheet and it needs a Promptinfo object to authenticate the biometrics.

At present, based on BiometricPrompt's methods there isn't a possible way to disable the system fingerprint bottom sheet. I'll however check if there are any ways to achieve it in future API releases. For now, I'm marking the issue as closed. Thank you.
